### ISSUE TITLE
Spotify: password reset due to suspicious activity

### ISSUE THREAD

**Issue by miraclx** [aviwad/LyricFever#39]
I restarted my computer earlier today, and on login, LyricFever mysteriously asked me to log in to Spotify, although I already had it setup with the `sp_dc` cookie (and "mysteriously" because it's never done that for months that I've had it set up).

Presented with both webview and advanced options for authentication, I went with the cookie option and all was fine.

<details>
<summary> Some hours later, the music stops, and I get this email </summary>
<img src="https://github.com/aviwad/LyricFever/assets/16881812/e88b28e5-ee65-4682-85ef-18ff51117e74" width="50%"/>
</details>

<details>
<summary> And well enough, the Spotify app has been logged out </summary>
<img src="https://github.com/aviwad/LyricFever/assets/16881812/19f1deb5-abbf-444d-982a-e910c9475925" width="50%" />
</details>

Anyone else have this experience? Worth noting that I'm behind a VPN, but I almost always am, and it's never been an issue.

And what do you think? Maybe their bot detection implementation is now more robust?

Interestingly, after resetting my password, turns out LyricFever still works, without needing to re-authenticate.

But all my Spotify clients were logged out, on all devices 😅

**Comment by miraclx** [comment]
> Interestingly, after resetting my password, turns out LyricFever still works, without needing to re-authenticate.

Update: went in for a song change, and LyricFever instantly disconnected, showing this:

<img src="https://github.com/aviwad/LyricFever/assets/16881812/2e84084a-8172-4c28-88aa-3407fba7f3f3" width="50%"/>

I'll hold off on reconnecting for now

**Comment by aviwad** [comment]
Hi. Two steps to this problem.

Step 1:
Since you previously set it up with the `sp_dc` code, Lyric Fever would display a Spotify prompt similar to this:
<img width="812" alt="Screenshot 2024-06-20 at 12 39 03 PM" src="https://github.com/aviwad/LyricFever/assets/25706524/e5874817-59c2-4711-94ff-af2768cea721">

I wasn't sure how to deal with this case, so I made it in a way where the Next button on the bottom right is blue/clickable when the sp-dc code is filled out. Maybe I should improve the UI so that it shows the sp-dc page if you selected it. That way you wouldn't have to re-authenticate. 

This is very very strange to me. My app has been running perfect all this while. I have a feeling it has to do with you *logging in* through the VPN. I have a big hunch it's to do with the VPN. Am at a loss for answers here. Very strange behaviour :(

**Comment by aviwad** [comment]
This is so so weird. Btw if you have logged in using cookies, the sign in page will still show the Spotify log in page, but the Next button in the bottom right is blue and clickable. I think I should fix the UI so that it remembers if you used Spotify or Cookie login but yes it is navigatble. About the suspicious activity, I have not received any report and it has been working on my end. I am really sorry I cannot help. I have a doubt it has something to do with the VPN. Perhaps because the cookie you are reusing was created when logging in else where without the VPN? Can you try using the Spotify login option (which generates brand new cookies)

**Comment by miraclx** [comment]
Alright, let me retry this.
